### ISSUE TITLE
ไม่ได้ Pack ทำเป็นตัวติดตั้งเหรอครับ

### ISSUE THREAD

**Issue by firdows** [kongvut/yii2-basic-adminlte3#3]

**Comment by kongvut** [comment]
ไม่ได้ทำเป็นตัวติดตั้งครับ
วัตถุประสงค์คือ ต้องการทำเป็นตัวอย่างการ แยก Custom Theme ออกมาใช้
แบบไม่ใช้ CDN หรือแบบ Import CSS/JS

ตามตัวอย่างจะใช้ ระบบ Assets ของ Yii จัดการครับ
ข้อดีคือ Asset เหล่านั้นลงผ่าน Composer เมื่อ Asset มีการอัพเดท
Theme ก็จะอัพเดทไปด้วยครับ
