### ISSUE TITLE
assets depends

### ISSUE THREAD

**Issue by paskuale75** [kongvut/yii2-basic-adminlte3#5]
why didn't you enter the asset as a dependency of the main asset ? tnx

**Comment by kongvut** [comment]
> why didn't you enter the asset as a dependency of the main asset ? tnx

I have separate asset depend on theme. So flexible and easy to add more themes in the future.

**Comment by paskuale75** [comment]
I think the theory is to create how many assets are needed for the expected themes, then update the dependencies in the appAsset file if necessary, or am I wrong? The modification would be done in one place only.

**Comment by kongvut** [comment]
> I think the theory is to create how many assets are needed for the expected themes, then update the dependencies in the appAsset file if necessary, or am I wrong? The modification would be done in one place only.

It's true, but this method will work for many themes and changing the site themes dynamically with assets depend on theme
